apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    name: test
spec:
  hostNetwork: true
  containers:
  - name: your-container
    image: your-container
    command:
    - bash
    - -c
    args:
    - python test.py
    ports:
    - hostPort: 12345
      containerPort: 12345
    volumeMounts:
    - name: ssh
      mountPath: /tmp
  volumes:
  - name: ssh
    hostPath:
      path: /tmp
