apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  hostNetwork: true
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 8086
    args:
    - cd /home && ./run191.sh
    command:
    - sh
    - -c
    image: oodaflow:example
    resources:
      limits:
      cambricon.com/mlu: '4'
    volumeMounts:
      - mountPath: /lib/modules
        name: start
      - mountPath: /dev
        name: dev
  volumes:
    - hostPath:
        path: /dev
      name: dev
    - hostPath:
        path: /lib/modules
      name: start